

[[object]]
name = "steak"
path = "objects/steak/steak_000/steak_000.urdf"
scale =  [0.1, 0.1, 0.1]
category = "steak"
model_path = "objects/fridge/10373"
# TODO: update states. steak.states[object_states.OnTop].set_value(obj, True, use_ray_casting_method=True)


[[object]]
name = "plate"
path = "objects/bowl/a1393437aac09108d627bfab5d10d45d/a1393437aac09108d627bfab5d10d45d.urdf"
scale = [0.8, 0.8, 0.8]
category = "plate"
model_path = "objects/bowl/a1393437aac09108d627bfab5d10d45d"
#TODO: obj.states[object_states.Dusty].set_value(True) obj.states[object_states.Stained].set_value(True)
[onject.states]
Dusty =true
Stained = true

[[object]]
name = "stove"
path = "objects/stove/101940/101940.urdf"
scale = [1.1,1.0, 1.0 ]
category = "stove"
model_path = "objects/stove/101940"
[object.states]
ToggledOn = false

[[object]]
name = "pan"
path = "objects/frying_pan/36_0/36_0.urdf"
scale = [1.3, 1.3, 1.0 ]
category = "vidalia_onion"
model_path = "objects/frying_pan/36_0"

[[object]]
name = "green_onion"
path = "objects/green_onion/green_onion_000/green_onion_000.urdf"
scale = [0.1,0.1,0.1]
category = "green_onion"
model_path = "objects/green_onion/green_onion_000"
[object.abilities]
#TODO: add abilities abilities {'burnable': {}, 'freezable': {}, 'cookable': {}, 'sliceable': {'slice_force': 0.0}}

[[object]]
name = "counter"
path = "objects/bottom_cabinet/46452/46452.urdf"
scale = [1.04, 0.97, 0.95]
category = "counter"
[object.avg_obj_dims]
density = 10000

[[object]]
name = "vidalia_onion"
path = "objects/vidalia_onion/18_1/18_1.urdf"
scale = [2.0, 2.0, 2.0]
category = "vidalia_onion"

[[object]]
name = "knife"
path = "objects/carving_knife/14_1/14_1.urdf"
scale = [1, 1, 1]
model_path = "objects/carving_knife/14_1"
category = "knife"
#TODO: abilities {'slicer': {}}

[[object]]
name = "chopping_board"
path = "objects/chopping_board/10_0/10_0.urdf"
scale = [1.2,1.2, 1.2]
model_path = "objects/chopping_board/10_0"
category = "chopping_board"
 
[[object]]
name = "sink"
path = "objects/sink/kitchen_sink/kitchen_sink.urdf"
scale = [1.2, 1.25, 1.25]
model_path = "objects/sink/kitchen_sink"
category = "sink"


[[object]]
name = "table_v"
path = "objects/breakfast_table/26670/26670.urdf"
scale = [1.2, 1.2, 1.3]
model_path = "objects/breakfast_table/26670"
category = "table_v"

[[object]]
name = "large_bowl"
path = "objects/bowl/5aad71b5e6cb3967674684c50f1db165/5aad71b5e6cb3967674684c50f1db165.urdf"
scale = [0.5, 0.5, 0.5]
model_path = "objects/bowl/5aad71b5e6cb3967674684c50f1db165"
category = "large_bowl"

[[object]]
name = "steak_bowl"
path = "objects/bowl/7d7bdea515818eb844638317e9e4ff18/7d7bdea515818eb844638317e9e4ff18.urdf"
scale = [0.5, 0.5, 0.5]
model_path = "objects/bowl/7d7bdea515818eb844638317e9e4ff18"
category = "steak_bowl"

[[object]]
name = "table_h"
path = "objects/breakfast_table/26670/26670.urdf"
scale = [1.2, 1.2, 1.3]
model_path = "objects/breakfast_table/26670"
category = "table_h"

[[object]]
name = "tray"
path = "objects/tray/tray_000/tray_000.urdf"
scale = [0.1, 0.1, 0.1]
model_path = "objects/tray/tray_000/"
category = "tray"
